apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-dashboard-cert
  namespace: kubernetes-dashboard
spec:
  secretName: kubernetes-dashboard-tls
  dnsNames:
    - dashboard-kube.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
